<?php

return [
    'public_pages' => [
        ['route_name' => 'frontend.home', 'page_name' => 'Home', 'path' => '/'],
        ['route_name' => 'frontend.partnerProgram', 'page_name' => 'Partner Program', 'path' => '/partner-program'],
        ['route_name' => 'frontend.livingInBristol', 'page_name' => 'Living in Bristol', 'path' => '/bristol'],
        ['route_name' => 'frontend.rentingTennessee', 'page_name' => 'Renting Tennessee', 'path' => '/renting-tennessee'],
        ['route_name' => 'frontend.moving-from-california', 'page_name' => 'Moving from California to Tennessee', 'path' => '/moving-from-california-to-tennessee'],
        ['route_name' => 'frontend.moving-from-new-york-city', 'page_name' => 'Moving from New York City to Tennessee', 'path' => '/moving-from-new-york-city-to-tennessee'],
        ['route_name' => 'frontend.moving-from-florida', 'page_name' => 'Moving from Florida to Tennessee', 'path' => '/moving-from-florida-to-tennessee'],
        ['route_name' => 'frontend.moving-from-texas', 'page_name' => 'Moving from Texas to Tennessee', 'path' => '/moving-from-texas-to-tennessee'],
        ['route_name' => 'frontend.moving-from-arizona', 'page_name' => 'Moving from Arizona to Tennessee', 'path' => '/moving-from-arizona-to-tennessee'],
        ['route_name' => 'frontend.moving-from-north-carolina', 'page_name' => 'Moving from North Carolina to Tennessee', 'path' => '/moving-from-north-carolina-to-tennessee'],
        ['route_name' => 'frontend.moving-from-virginia', 'page_name' => 'Moving from Virginia to Tennessee', 'path' => '/moving-from-virginia-to-tennessee'],
        ['route_name' => 'frontend.moving-from-illinois', 'page_name' => 'Moving from Illinois to Tennessee', 'path' => '/moving-from-illinois-to-tennessee'],
        ['route_name' => 'frontend.is-tennessee-cheaper-than-texas', 'page_name' => 'Is Tennessee Cheaper Than Texas', 'path' => '/is-tennessee-cheaper-than-texas'],
        ['route_name' => 'frontend.is-tennessee-cheaper-than-florida', 'page_name' => 'Is Tennessee Cheaper Than Florida', 'path' => '/is-tennessee-cheaper-than-florida'],
        ['route_name' => 'frontend.livingInChattanooga', 'page_name' => 'Living in Chattanooga', 'path' => '/chattanooga'],
        ['route_name' => 'frontend.home-for-sale', 'page_name' => 'Homes for Sale', 'path' => '/homes-for-sale'],
        ['route_name' => 'frontend.movingChecklist', 'page_name' => 'Moving Checklist', 'path' => '/moving-checklist'],
        ['route_name' => 'frontend.city-comparison', 'page_name' => 'City Comparison', 'path' => '/city-comparison'],
        ['route_name' => 'frontend.realEstateAgents', 'page_name' => 'Real Estate Agents', 'path' => '/real-estate-agents'],
        ['route_name' => 'frontend.rentals', 'page_name' => 'Rentals', 'path' => '/rentals'],
        ['route_name' => 'frontend.why-tennessee', 'page_name' => 'Why Tennessee', 'path' => '/why-tennessee'],
        ['route_name' => 'frontend.tennessee-relocation', 'page_name' => 'Tennessee Relocation', 'path' => '/tennessee-relocation'],
        ['route_name' => 'frontend.livetennessee', 'page_name' => 'Live Tennessee', 'path' => '/live-tennessee'],
        ['route_name' => 'frontend.renting-buy', 'page_name' => 'Renting vs Buying', 'path' => '/renting-buy'],
        ['route_name' => 'frontend.livingInNashville', 'page_name' => 'Living in Nashville', 'path' => '/living-in-nashville'],
        ['route_name' => 'frontend.cost-of-renting-tennessee', 'page_name' => 'Cost of Renting Tennessee', 'path' => '/cost-of-renting-tennessee'],
        ['route_name' => 'frontend.moving-tennessee-renting', 'page_name' => 'Moving Tennessee Renting', 'path' => '/moving-tennessee-renting'],
        ['route_name' => 'frontend.livingInCookeville', 'page_name' => 'Living in Cookeville', 'path' => '/living-in-cookeville'],
        ['route_name' => 'frontend.livingInKnoxville', 'page_name' => 'Living in Knoxville', 'path' => '/living-in-knoxville'],
        ['route_name' => 'frontend.livingInJohnsonCity', 'page_name' => 'Living in Johnson City', 'path' => '/living-in-johnson-city'],
        ['route_name' => 'frontend.livingInFranklin', 'page_name' => 'Living in Franklin', 'path' => '/living-in-franklin'],
        ['route_name' => 'frontend.living-in-memphis', 'page_name' => 'Living in Memphis', 'path' => '/living-in-memphis'],
        ['route_name' => 'frontend.livingInClarksville', 'page_name' => 'Living in Clarksville', 'path' => '/living-in-clarksville'],
        ['route_name' => 'frontend.livingInMurfreesboro', 'page_name' => 'Living in Murfreesboro', 'path' => '/living-in-murfreesboro'],
        ['route_name' => 'frontend.livingInKingsport', 'page_name' => 'Living in Kingsport', 'path' => '/living-in-kingsport'],
        ['route_name' => 'frontend.livingInJackson', 'page_name' => 'Living in Jackson', 'path' => '/living-in-jackson'],
        ['route_name' => 'frontend.cost-of-living-in-tennessee', 'page_name' => 'Cost of Living in Tennessee', 'path' => '/cost-of-living-in-tennessee'],
        ['route_name' => 'frontend.pros-cons-tennessee', 'page_name' => 'Pros and Cons Tennessee', 'path' => '/pros-cons-living-in-tennessee'],
        ['route_name' => 'frontend.privacy-policy', 'page_name' => 'Privacy Policy', 'path' => '/privacy-policy'],
        ['route_name' => 'frontend.get-in-touch', 'page_name' => 'Get In Touch', 'path' => '/get-in-touch'],
        ['route_name' => 'frontend.list-rental-property', 'page_name' => 'List Rental Property', 'path' => '/list-rental-property'],
        ['route_name' => 'frontend.buying', 'page_name' => 'Buying in Tennessee', 'path' => '/buying'],
        ['route_name' => 'frontend.cost-of-buying-tennessee', 'page_name' => 'Cost of Buying Tennessee', 'path' => '/cost-of-buying-tennessee'],
        ['route_name' => 'frontend.realtor', 'page_name' => 'Realtor', 'path' => '/realtor'],
        ['route_name' => 'frontend.single-product.listing', 'page_name' => 'Listing Detail', 'path' => '/single-product/listing/{listing_id}'],
        ['route_name' => 'frontend.single-product.rental', 'page_name' => 'Rental Detail', 'path' => '/single-product/rental/{rental_id}'],
        ['route_name' => 'frontend.mortgage-calculator', 'page_name' => 'Mortgage Calculator', 'path' => '/mortgage-calculator'],
    ],
];

